#spring.application.name=learningDocker
spring:
  datasource:
    url: jdbc:postgresql://postgres-sql-test:5432/demo_test
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
